## Filter out samples from each count matrix for RA patients analysis

### Change sample name for different sample names matrix

In [23]:
import pandas as pd
# Load Matrix and metadata
bacteria_matrix = pd.read_csv('./99_Original_Data/bacteria_final_normalized_count.tsv', sep = '\t', index_col=0)
fungi_matrix = pd.read_csv('./99_Original_Data/fungi_final_normalized_count.tsv', sep = '\t', index_col=0)
virus_matrix = pd.read_csv('./99_Original_Data/virus_final_normalized_count.tsv', sep = '\t', index_col=0)
MetaCyc_pathway = pd.read_csv('./99_Original_Data/pathabundance_merged_filtered_final.tsv', sep = '\t', index_col=0)
metadata = pd.read_csv('./01_Processed_Data/cleaned_metadata.tsv', sep = '\t', index_col=1)

In [ ]:
virus_matrix = virus_matrix.T
virus_matrix.fillna(0, inplace=True)
fungi_matrix.index = fungi_matrix.index.str.replace('_bracken', '')
MetaCyc_pathway = MetaCyc_pathway.T
MetaCyc_pathway.index = MetaCyc_pathway.index.str.replace('_Abundance', '')

In [25]:
# Make relative abundance matrix for all matrices
bacteria_matrix_rel_abundance = bacteria_matrix.div(bacteria_matrix.sum(axis=1), axis=0)
fungi_matrix_rel_abundance = fungi_matrix.div(fungi_matrix.sum(axis=1), axis=0)
virus_matrix_rel_abundance = virus_matrix.div(virus_matrix.sum(axis=1), axis=0)
MetaCyc_pathway_rel_abundance = MetaCyc_pathway.div(MetaCyc_pathway.sum(axis=1), axis=0)
# Save the matrices
bacteria_matrix_rel_abundance.to_csv('./01_Processed_Data/bacteria_matrix_rel_abundance.tsv', sep='\t', index=True)
fungi_matrix_rel_abundance.to_csv('./01_Processed_Data/fungi_matrix_rel_abundance.tsv', sep='\t', index=True)
virus_matrix_rel_abundance.to_csv('./01_Processed_Data/virus_matrix_rel_abundance.tsv', sep='\t', index=True)
MetaCyc_pathway_rel_abundance.to_csv('./01_Processed_Data/MetaCyc_pathway_rel_abundance.tsv', sep='\t', index=True)

In [28]:
bacteria_matrix_rel_abundance

tax_name,s__Scardovia inopinata,s__Rothia mucilaginosa,s__Rothia mucilaginosa,s__Rothia mucilaginosa_A,s__Rothia sp015265375,s__Rothia mucilaginosa,s__Rothia sp001808955,s__Rothia mucilaginosa,s__Rothia mucilaginosa_B,s__Rothia mucilaginosa_B,...,s__HROM_Genome_5095,s__HROM_Genome_5096,s__HROM_Genome_5100,s__Fretibacterium fastidiosum,s__HROM_Genome_5102,s__HROM_Genome_5103,s__CAJPSE01 sp905373185,s__HROM_Genome_5105,s__HROM_Genome_5106,s__Pyramidobacter piscolens
saliva swab,,,,,,,,,,,,,,,,,,,,,
sample_2022120210001,1.172340e-04,0.058734,0.000000,0.100009,0.000000,0.003064,0.035585,0.000343,0.000000,0.030962,...,0.000000e+00,0.000000e+00,0.000000e+00,1.582429e-04,5.974042e-05,1.102978e-04,6.347288e-06,5.738671e-06,0.000000e+00,1.159289e-05
sample_2022120210004,0.000000e+00,0.002217,0.000000,0.037443,0.000000,0.000000,0.001241,0.000000,0.000000,0.019168,...,0.000000e+00,0.000000e+00,0.000000e+00,6.814846e-07,3.714490e-07,6.127518e-07,1.087255e-06,0.000000e+00,5.595637e-07,0.000000e+00
sample_2022120210037,0.000000e+00,0.030174,0.000718,0.001379,0.000000,0.000000,0.028999,0.000000,0.000000,0.058345,...,0.000000e+00,0.000000e+00,0.000000e+00,1.825525e-04,1.043002e-04,3.805423e-05,3.015480e-04,1.353253e-05,2.077823e-05,0.000000e+00
sample_2022120210043,0.000000e+00,0.009444,0.004925,0.000019,0.012713,0.000000,0.142658,0.000000,0.000000,0.013357,...,0.000000e+00,0.000000e+00,5.582001e-04,0.000000e+00,9.242269e-07,0.000000e+00,0.000000e+00,5.168406e-07,0.000000e+00,0.000000e+00
sample_2022120210051,0.000000e+00,0.018320,0.000410,0.000468,0.001278,0.000288,0.053971,0.000000,0.000026,0.010309,...,5.192256e-07,0.000000e+00,4.985958e-07,0.000000e+00,1.293620e-06,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
sample_2022120210069,0.000000e+00,0.020145,0.001678,0.316843,0.000000,0.000000,0.008706,0.000000,0.007483,0.078474,...,0.000000e+00,0.000000e+00,1.281358e-06,2.385988e-07,1.520589e-06,0.000000e+00,0.000000e+00,5.169347e-07,0.000000e+00,5.035549e-06
sample_2022120210002,0.000000e+00,0.000049,0.000000,0.175807,0.000000,0.000000,0.004984,0.000000,0.000000,0.000098,...,0.000000e+00,0.000000e+00,0.000000e+00,2.171064e-04,6.857178e-05,7.181641e-04,1.227786e-04,1.215903e-04,1.695744e-05,2.184772e-05
sample_2022120210003,1.112087e-04,0.001128,0.000000,0.037065,0.000000,0.000000,0.004575,0.000050,0.000000,0.000499,...,1.970646e-05,4.958078e-06,3.261245e-05,2.435194e-05,3.040253e-05,4.530819e-06,6.995183e-06,5.739389e-06,2.547970e-05,1.877449e-06
sample_2022120210011,4.924795e-05,0.032498,0.000103,0.015628,0.000029,0.000000,0.002191,0.000000,0.000000,0.111253,...,0.000000e+00,0.000000e+00,0.000000e+00,1.313734e-06,1.614969e-06,1.459736e-06,3.848463e-06,3.262910e-07,0.000000e+00,0.000000e+00
sample_2022120210013,7.507799e-07,0.000808,0.000000,0.142967,0.000000,0.000000,0.000953,0.000000,0.000000,0.001058,...,4.513309e-06,3.843989e-06,0.000000e+00,0.000000e+00,0.000000e+00,5.671760e-07,3.422305e-06,1.164342e-06,5.190950e-07,3.330197e-07
sample_2022120210014,9.292461e-07,0.000910,0.000000,0.000169,0.000040,0.000000,0.007298,0.000000,0.000000,0.028422,...,8.431200e-06,1.495288e-06,9.357367e-03,3.805308e-06,5.718752e-06,4.942067e-07,2.048812e-06,4.948999e-06,1.627636e-06,1.079522e-06
sample_2022120210016,0.000000e+00,0.009024,0.000301,0.000036,0.003605,0.000000,0.050910,0.000000,0.000021,0.001505,...,5.775811e-07,0.000000e+00,4.187245e-05,2.192489e-05,1.072909e-05,1.280743e-05,7.438672e-05,4.890415e-06,2.535711e-06,0.000000e+00
sample_2022120210021,0.000000e+00,0.002947,0.001358,0.058466,0.000000,0.000000,0.007636,0.000000,0.000000,0.000975,...,0.000000e+00,0.000000e+00,2.374341e-05,1.458999e-04,1.268956e-04,1.039196e-05,4.361887e-04,1.300817e-05,7.565571e-06,5.084733e-06
sample_2022120210023,0.000000e+00,0.015432,0.000546,0.000141,0.000178,0.000000,0.003189,0.000000,0.000199,0.016297,...,0.000000e+00,0.000000e+00,6.537264e-04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
sample_2022120210025,0.000000e+00,0.005029,0.000230,0.316411,0.000000,0.000000,0.009555,0.000000,0.000000,0.015783,...,0.000000e+00,0.000000e+00,1.286974e-06,4.597684e-05,1.003374e-05,9.071767e-06,1.532312e-04,3.139493e-06,4.439962e-06,0.000000e+00
sample_2022120210026,0.000000e+00,0.104676,0.000103,0.000054,0.000000,0.000000,0.033134,0.000057,0.000000,0.032181,...,0.000000e+00,0.000000e+00,2.600035e-03,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
sample_2022120210028,0.000000e+00,0.007872,0.000119,0.048686,0.000000,0.000000,0.000780,0.000000,0.000000,0.000063,...,1.482622e-06,0.000000e+00,0.000000e+00,4.811812e-06,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
sample_2022120210029,0.000000e+00,0.006671,0.001003,0.037642,0.000017,0.000091,0.011929,0.000000,0.000000,0.003314,...,0.000000e+00,0.000000e+00,1.257863e-06,0.000000e+00,7.352143e-07,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
sample_2022120210033,3.640857e-06,0.002501,0.000410,0.008399,0.002744,0.000000,0.048640,0.000011,0.000017,0.004071,...,0.000000e+00,0.000000e+00,2.025548e-05,4.883581e-07,1.527663e-06,0.000000e+00,1.558274e-06,0.000000e+00,0.000000e+00,0.000000e+00
sample_2022120210039,0.000000e+00,0.007046,0.009302,0.030808,0.009503,0.000000,0.030093,0.000000,0.000000,0.003990,...,1.101402e-05,0.000000e+00,0.000000e+00,2.931622e-05,8.864296e-06,2.282578e-06,4.861127e-05,7.143062e-07,1.483720e-06,0.000000e+00
sample_2022120210040,0.000000e+00,0.000357,0.000000,0.027103,0.000000,0.000000,0.000531,0.000000,0.000000,0.000011,...,0.000000e+00,0.000000e+00,3.714958e-07,1.566885e-06,4.646665e-06,6.078565e-07,6.719907e-06,1.521773e-06,0.000000e+00,0.000000e+00
sample_2022120210042,0.000000e+00,0.009585,0.000000,0.002381,0.000101,0.010544,0.020443,0.000000,0.000695,0.033090,...,0.000000e+00,0.000000e+00,0.000000e+00,5.480514e-05,7.375370e-06,6.474465e-05,4.372472e-05,3.680763e-06,4.853835e-06,0.000000e+00
sample_2022120210044,2.898123e-07,0.001931,0.000000,0.292199,0.000000,0.000000,0.004605,0.000092,0.000000,0.002330,...,0.000000e+00,0.000000e+00,0.000000e+00,2.639464e-06,3.122962e-06,2.729433e-07,6.698998e-06,7.637052e-07,0.000000e+00,0.000000e+00
sample_2022120210046,0.000000e+00,0.059846,0.001174,0.001534,0.000000,0.000000,0.081290,0.000000,0.000000,0.140562,...,3.913199e-05,1.342936e-05,4.829916e-04,2.104325e-06,4.247439e-06,2.418818e-06,1.552659e-06,0.000000e+00,9.182106e-06,0.000000e+00
sample_2022120210047,0.000000e+00,0.008946,0.000000,0.000155,0.000000,0.000000,0.151089,0.000000,0.000000,0.002291,...,1.385854e-06,0.000000e+00,9.751747e-03,0.000000e+00,3.998616e-07,0.000000e+00,0.000000e+00,6.837543e-07,0.000000e+00,0.000000e+00
sample_2022120210048,0.000000e+00,0.007409,0.001120,0.001198,0.000000,0.000000,0.183750,0.000000,0.000983,0.000222,...,0.000000e+00,0.000000e+00,0.000000e+00,7.185663e-06,2.571775e-06,8.061017e-07,2.743271e-05,1.057090e-06,6.746889e-06,0.000000e+00
sample_2022120210049,0.000000e+00,0.007382,0.005436,0.140892,0.000000,0.000000,0.015124,0.000030,0.000000,0.004609,...,0.000000e+00,0.000000e+00,5.897003e-04,4.710595e-06,4.690717e-06,1.321109e-06,2.160460e-05,8.032270e-07,6.281118e-07,0.000000e+00
sample_2022120210050,0.000000e+00,0.004443,0.000000,0.017910,0.004760,0.000000,0.074613,0.000000,0.000000,0.004997,...,0.000000e+00,0.000000e+00,0.000000e+00,3.961085e-06,1.360587e-05,0.000000e+00,1.316760e-05,0.000000e+00,0.000000e+00,0.000000e+00
sample_2022120210052,0.000000e+00,0.001222,0.000000,0.038311,0.000000,0.000000,0.005308,0.000000,0.000000,0.000184,...,0.000000e+00,0.000000e+00,0.000000e+00,4.945440e-06,6.488579e-07,3.821064e-06,2.073177e-06,0.000000e+00,0.000000e+00,0.000000e+00
sample_2022120210053,4.792306e-07,0.002915,0.000043,0.071558,0.000022,0.000448,0.004974,0.000000,0.000015,0.005227,...,0.000000e+00,1.522006e-06,2.127117e-04,4.265662e-06,2.971621e-06,2.381043e-06,7.355030e-07,0.000000e+00,0.000000e+00,0.000000e+00
sample_2022120210056,0.000000e+00,0.002562,0.000000,0.300715,0.000000,0.000000,0.013437,0.000000,0.000000,0.000500,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.612675e-06,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
sample_2022120210058,0.000000e+00,0.005511,0.000000,0.000725,0.000000,0.000000,0.078187,0.000000,0.000000,0.018429,...,4.268607e-06,0.000000e+00,5.344823e-07,0.000000e+00,2.730122e-06,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
sample_2022120210065,0.000000e+00,0.003751,0.000963,0.051495,0.000000,0.000000,0.006986,0.000000,0.000000,0.002118,...,0.000000e+00,4.008050e-07,2.802457e-07,7.594769e-06,2.962384e-06,7.065057e-06,4.094205e-06,1.013341e-06,6.295448e-06,0.000000e+00
sample_10810599,0.000000e+00,0.001993,0.000000,0.042463,0.000000,0.000000,0.001865,0.000000,0.000000,0.002018,...,4.602604e-04,1.067269e-04,1.609084e-05,1.635587e-03,1.053006e-03,8.383144e-04,2.156966e-03,1.386732e-04,1.302937e-03,1.213559e-05
sample_10816884,0.000000e+00,0.016148,0.002847,0.047979,0.000000,0.002346,0.037193,0.000000,0.000000,0.028255,...,0.000000e+00,0.000000e+00,0.000000e+00,1.666998e-05,1.524825e-05,4.047263e-05,2.551161e-05,1.560929e-05,2.047757e-06,0.000000e+00

In [26]:
# filter our only samples with follow-up DAS28ESR value (DAS_28_ESR.1)
follow_up_samples = metadata[metadata['DAS_28_ESR.1'].notna()].index
# Filter matrices to keep only follow-up samples
bacteria_matrix = bacteria_matrix.loc[follow_up_samples]
fungi_matrix = fungi_matrix.loc[follow_up_samples]
virus_matrix = virus_matrix.loc[follow_up_samples]
MetaCyc_pathway = MetaCyc_pathway.loc[follow_up_samples]
# Do the same also for relative abundance matrices
bacteria_matrix_rel_abundance = bacteria_matrix_rel_abundance.loc[follow_up_samples]
fungi_matrix_rel_abundance = fungi_matrix_rel_abundance.loc[follow_up_samples]
virus_matrix_rel_abundance = virus_matrix_rel_abundance.loc[follow_up_samples]
MetaCyc_pathway_rel_abundance = MetaCyc_pathway_rel_abundance.loc[follow_up_samples]
# Save the filtered matrices
bacteria_matrix.to_csv('./01_Processed_Data/bacteria_matrix_filtered.tsv', sep='\t', index=True)
fungi_matrix.to_csv('./01_Processed_Data/fungi_matrix_filtered.tsv', sep='\t', index=True)
virus_matrix.to_csv('./01_Processed_Data/virus_matrix_filtered.tsv', sep='\t', index=True)
MetaCyc_pathway.to_csv('./01_Processed_Data/MetaCyc_pathway_filtered.tsv', sep='\t', index=True)
bacteria_matrix_rel_abundance.to_csv('./01_Processed_Data/bacteria_matrix_rel_abundance_filtered.tsv', sep='\t', index=True)
fungi_matrix_rel_abundance.to_csv('./01_Processed_Data/fungi_matrix_rel_abundance_filtered.tsv', sep='\t', index=True)
virus_matrix_rel_abundance.to_csv('./01_Processed_Data/virus_matrix_rel_abundance_filtered.tsv', sep='\t', index=True)
MetaCyc_pathway_rel_abundance.to_csv('./01_Processed_Data/MetaCyc_pathway_rel_abundance_filtered.tsv', sep='\t', index=True)

In [27]:
bacteria_matrix

tax_name,s__Scardovia inopinata,s__Rothia mucilaginosa,s__Rothia mucilaginosa,s__Rothia mucilaginosa_A,s__Rothia sp015265375,s__Rothia mucilaginosa,s__Rothia sp001808955,s__Rothia mucilaginosa,s__Rothia mucilaginosa_B,s__Rothia mucilaginosa_B,...,s__HROM_Genome_5095,s__HROM_Genome_5096,s__HROM_Genome_5100,s__Fretibacterium fastidiosum,s__HROM_Genome_5102,s__HROM_Genome_5103,s__CAJPSE01 sp905373185,s__HROM_Genome_5105,s__HROM_Genome_5106,s__Pyramidobacter piscolens
saliva swab,,,,,,,,,,,,,,,,,,,,,
sample_2022120210001,166.313856,8.332305e+04,0.000000,1.418774e+05,0.000000,4346.276549,5.048323e+04,486.611437,0.000000,4.392381e+04,...,0.000000,0.000000,0.000000,224.491078,84.750652,156.473867,9.004570,8.141157,0.000000,16.446229
sample_2022120210004,0.000000,5.674339e+04,0.000000,9.584893e+05,0.000000,0.000000,3.176483e+04,0.000000,0.000000,4.906763e+05,...,0.000000,0.000000,0.000000,17.445114,9.508610,15.685644,27.832308,0.000000,14.324099,0.000000
sample_2022120210037,0.000000,1.334770e+05,3175.356635,6.100173e+03,0.000000,0.000000,1.282766e+05,0.000000,0.000000,2.580890e+05,...,0.000000,0.000000,0.000000,807.525167,461.374284,168.333745,1333.904278,59.861447,91.912972,0.000000
sample_2022120210043,0.000000,1.225020e+05,63885.954967,2.476390e+02,164910.562962,0.000000,1.850571e+06,0.000000,0.000000,1.732665e+05,...,0.000000,0.000000,7240.999119,0.000000,11.989117,0.000000,0.000000,6.704482,0.000000,0.000000
sample_2022120210051,0.000000,3.746990e+05,8383.829728,9.576749e+03,26137.249254,5900.184838,1.103886e+06,0.000000,528.217831,2.108548e+05,...,10.619852,0.000000,10.197906,0.000000,26.458740,0.000000,0.000000,0.000000,0.000000,0.000000
sample_2022120210069,0.000000,5.038817e+05,41960.894587,7.925193e+06,0.000000,0.000000,2.177615e+05,0.000000,187182.309137,1.962866e+06,...,0.000000,0.000000,32.050563,5.968065,38.034439,0.000000,0.000000,12.930073,0.000000,125.954048
sample_2022120210002,0.000000,2.965873e+02,0.000000,1.068417e+06,0.000000,0.000000,3.029108e+04,0.000000,0.000000,5.960290e+02,...,0.000000,0.000000,0.000000,1319.401551,416.725159,4364.434906,746.151426,738.929703,103.053938,132.773217
sample_2022120210003,1568.184283,1.590340e+04,0.000000,5.226672e+05,0.000000,0.000000,6.450982e+04,710.189664,0.000000,7.042414e+03,...,277.886127,69.915208,459.877015,343.393306,428.714276,63.890308,98.640973,80.932676,359.296161,26.474418
sample_2022120210011,1084.205207,7.154568e+05,2278.262872,3.440581e+05,629.048392,0.000000,4.823037e+04,0.000000,0.000000,2.449259e+06,...,0.000000,0.000000,0.000000,28.922163,35.553932,32.136442,84.724819,7.183374,0.000000,0.000000
sample_2022120210013,12.660570,1.363073e+04,0.000000,2.410878e+06,0.000000,0.000000,1.606697e+04,0.000000,0.000000,1.784290e+04,...,76.108939,64.822047,0.000000,0.000000,0.000000,9.564417,57.711109,19.634555,8.753616,5.615786
sample_2022120210014,17.264414,1.690285e+04,0.000000,3.148225e+03,736.035451,0.000000,1.355842e+05,0.000000,0.000000,5.280597e+05,...,156.642817,27.780877,173850.022449,70.698622,106.248379,9.181841,38.064774,91.947183,30.239766,20.056377
sample_2022120210016,0.000000,1.175302e+05,3916.569254,4.737242e+02,46945.122396,0.000000,6.630441e+05,0.000000,275.305553,1.960450e+04,...,7.522395,0.000000,545.345182,285.548979,139.735222,166.803438,968.809888,63.692580,33.025007,0.000000
sample_2022120210021,0.000000,3.255002e+03,1499.745365,6.457232e+04,0.000000,0.000000,8.433375e+03,0.000000,0.000000,1.076384e+03,...,0.000000,0.000000,26.223188,161.137768,140.148640,11.477301,481.744503,14.366747,8.355725,5.615786
sample_2022120210023,0.000000,2.812424e+05,9949.746860,2.572694e+03,3242.906497,0.000000,5.812210e+04,0.000000,3625.515073,2.970035e+05,...,0.000000,0.000000,11914.068298,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
sample_2022120210025,0.000000,3.605686e+04,1652.517768,2.268439e+06,0.000000,0.000000,6.849995e+04,0.000000,0.000000,1.131541e+05,...,0.000000,0.000000,9.226677,329.620847,71.934700,65.038038,1098.557558,22.507904,31.831332,0.000000
sample_2022120210026,0.000000,2.837111e+06,2794.757945,1.473452e+03,0.000000,0.000000,8.980691e+05,1544.639845,0.000000,8.722240e+05,...,0.000000,0.000000,70470.932145,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
sample_2022120210028,0.000000,9.162399e+04,1389.607120,5.666897e+05,0.000000,0.000000,9.078306e+03,0.000000,0.000000,7.298044e+02,...,17.257259,0.000000,0.000000,56.007999,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
sample_2022120210029,0.000000,1.725414e+05,25943.329867,9.736517e+05,435.938971,2362.497009,3.085476e+05,0.000000,0.000000,8.571118e+04,...,0.000000,0.000000,32.536177,0.000000,19.017220,0.000000,0.000000,0.000000,0.000000,0.000000
sample_2022120210033,65.029293,4.466140e+04,7329.078398,1.500087e+05,49010.283385,0.000000,8.687613e+05,200.902951,302.528750,7.271996e+04,...,0.000000,0.000000,361.782868,8.722557,27.285576,0.000000,27.832308,0.000000,0.000000,0.000000
sample_2022120210039,0.000000,7.557712e+04,99778.143482,3.304705e+05,101939.578208,0.000000,3.228069e+05,0.000000,0.000000,4.279930e+04,...,118.145853,0.000000,0.000000,314.471142,95.086098,24.484908,521.446471,7.662265,15.915666,0.000000
sample_2022120210040,0.000000,6.062491e+03,0.000000,4.605791e+05,0.000000,0.000000,9.031234e+03,0.000000,0.000000,1.827822e+02,...,0.000000,0.000000,6.312990,26.626754,78.962803,10.329571,114.194321,25.860145,0.000000,0.000000
sample_2022120210042,0.000000,1.359278e+05,0.000000,3.376374e+04,1428.565791,149525.195313,2.899128e+05,0.000000,9856.553513,4.692762e+05,...,0.000000,0.000000,0.000000,777.225757,104.594708,918.184061,620.087444,52.199182,68.835256,0.000000
sample_2022120210044,6.905766,4.600570e+04,0.000000,6.962646e+06,0.000000,0.000000,1.097346e+05,2190.885229,0.000000,5.551194e+04,...,0.000000,0.000000,0.000000,62.894228,74.415207,6.503804,159.626471,18.197880,0.000000,0.000000
sample_2022120210046,0.000000,7.572546e+05,14851.342829,1.940710e+04,0.000000,0.000000,1.028596e+06,0.000000,0.000000,1.778574e+06,...,495.150599,169.926367,6111.459588,26.626754,53.744316,30.606135,19.646335,0.000000,116.184362,0.000000
sample_2022120210047,0.000000,1.942410e+05,0.000000,3.361928e+03,0.000000,0.000000,3.280432e+06,0.000000,0.000000,4.975165e+04,...,30.089581,0.000000,211729.417145,0.000000,8.681774,0.000000,0.000000,14.845639,0.000000,0.000000
sample_2022120210048,0.000000,7.384542e+04,11163.932180,1.194445e+04,0.000000,0.000000,1.831371e+06,0.000000,9794.642694,2.210605e+03,...,0.000000,0.000000,0.000000,71.616786,25.631905,8.034111,273.411494,10.535615,67.243689,0.000000
sample_2022120210049,0.000000,7.481723e+04,55093.103776,1.428016e+06,0.000000,0.000000,1.532943e+05,306.116235,0.000000,4.671852e+04,...,0.000000,0.000000,5976.944347,47.744524,47.543049,13.390184,218.974774,8.141157,6.366266,0.000000
sample_2022120210050,0.000000,3.604545e+04,0.000000,1.453045e+05,38620.552564,0.000000,6.053250e+05,0.000000,0.000000,4.053704e+04,...,0.000000,0.000000,0.000000,32.135737,110.382557,0.000000,106.826946,0.000000,0.000000,0.000000
sample_2022120210052,0.000000,1.713362e+04,0.000000,5.370161e+05,0.000000,0.000000,7.441035e+04,0.000000,0.000000,2.585000e+03,...,0.000000,0.000000,0.000000,69.321376,9.095192,53.560737,29.060204,0.000000,0.000000,0.000000
sample_2022120210053,10.934129,6.650269e+04,971.703541,1.632668e+06,492.318043,10220.435779,1.134854e+05,0.000000,335.460036,1.192606e+05,...,0.000000,34.726097,4853.232191,97.325375,67.800522,54.325890,16.781244,0.000000,0.000000,0.000000
sample_2022120210056,0.000000,2.148547e+04,0.000000,2.521941e+06,0.000000,0.000000,1.126861e+05,0.000000,0.000000,4.194278e+03,...,0.000000,0.000000,0.000000,0.000000,21.911144,0.000000,0.000000,0.000000,0.000000,0.000000
sample_2022120210058,0.000000,8.512715e+04,0.000000,1.120475e+04,0.000000,0.000000,1.207652e+06,0.000000,0.000000,2.846467e+05,...,65.931581,0.000000,8.255448,0.000000,42.168617,0.000000,0.000000,0.000000,0.000000,0.000000
sample_2022120210065,0.000000,7.799282e+04,20018.514081,1.070787e+06,0.000000,0.000000,1.452577e+05,0.000000,0.000000,4.403507e+04,...,0.000000,8.334263,5.827375,157.924194,61.599255,146.909450,85.134118,21.071229,130.906353,0.000000
sample_10810599,0.000000,1.383343e+03,0.000000,2.947500e+04,0.000000,0.000000,1.294701e+03,0.000000,0.000000,1.400447e+03,...,319.480548,74.082340,11.169136,1135.309686,730.922700,581.899149,1497.214436,96.257207,904.407724,8.423678
sample_10816884,0.000000,5.647707e+04,9958.184871,1.678080e+05,0.000000,8203.451153,1.300838e+05,0.000000,0.000000,9.882250e+04,...,0.000000,0.000000,0.000000,58.303409,53.330898,141.553376,89.227104,54.593640,7.162050,0.000000